// <autogenerated />
#nullable enable

namespace TelegramToMatrixForward.Dto.Telegram;

internal sealed record Update(
    int UpdateId,
    Message? Message);

internal sealed record UpdateArrayResponse(
    bool Ok,
    Update[]? Result,
    string? Description);

internal sealed record TelegramResponse<T>(
    bool Ok,
    T? Result,
    string? Description);

internal sealed record TelegramResponseUpdate(
    bool Ok,
    Update[]? Result,
    string? Description);

internal sealed record GetUpdatesRequest(
    int Offset,
    int Timeout,
    int? AllowedUpdates);
