// <auto-generated/>
using System.Text.Json.Serialization;
using TelegramToMatrixForward.Dto.Matrix;

namespace TelegramToMatrixForward.Dto;

[JsonSourceGenerationOptions(
        PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResult))]
[JsonSerializable(typeof(SyncUpdate))]
[JsonSerializable(typeof(RoomsData))]
[JsonSerializable(typeof(RoomData))]
[JsonSerializable(typeof(TimelineData))]
[JsonSerializable(typeof(RoomEvent))]
[JsonSerializable(typeof(MessageContent))]
[JsonSerializable(typeof(MediaInfo))]
[JsonSerializable(typeof(InviteData))]
[JsonSerializable(typeof(InviteState))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
internal sealed partial class MatrixJsonContext : JsonSerializerContext
{
}
