// <auto-generated/>
using System.Text.Json.Serialization;
using TelegramToMatrixForward.Dto.Telegram;

namespace TelegramToMatrixForward.Dto;

[JsonSourceGenerationOptions(
        PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(Update))]
[JsonSerializable(typeof(TelegramResponse<Message>))]
[JsonSerializable(typeof(TelegramResponse<FileResponse>))]
[JsonSerializable(typeof(UpdateArrayResponse))]
[JsonSerializable(typeof(TelegramResponseUpdate))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(MediaInfo))]
[JsonSerializable(typeof(FileResponse))]
[JsonSerializable(typeof(Chat))]
[JsonSerializable(typeof(Qualitiy))]
[JsonSerializable(typeof(MessageEntity))]
internal sealed partial class TelegramJsonContext : JsonSerializerContext
{
}
